title: Digital Transformation Agency
email: web.team@digital.gov.au
description: > # this means to ignore newlines until "baseurl:"
  Driving the digital transformation of government information and services,
  making them simpler, clearer, faster.
baseurl: "" # bin/cibuild.sh may override this
url: "http://localhost:4000" # bin/cibuild.sh may override this
permalink: "/:categories/:title/"
timezone: Australia/Canberra
twitter: DTA
google_tag_manager: GTM-KR7JDF
tag_dir: /tags # for tags pages created by jekyll-archives

# Because there is no way to instantiate an empty array, and we need to merge two filtered
# collections together -- this is used on the News page layout and feed.xml.
empty-array: []

collections:
  assessment-reports:
    output: true
  projects:
    output: false
  teams:
    output: true
  leadership-group:
    output: true
  staff:
    output: false

# Build settings
markdown: kramdown
future: true # posts dated in the future will be published

gems:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-archives


exclude:
  - _config-*.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - bin
  - circle.yml
  - README.md
  - manifest*.yml
  - ld_library_path
  - config.ru
  - node_modules

assets:
  assets:
    - "*.png"
    - "*.jpg"
    - "bundle.css"
  sources:
    - _assets/js/vendor
    - _assets/scss
    - _assets/vendor
    - images/transformation-agenda

jekyll-archives:
  enabled:
    - 'tags'
  layout: tag-archive
  permalinks:
    tag: '/tags/:name/'


defaults:
  -
    scope:
      path: "" # empty string means all files
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: post


# Config for http://prose.io editor.
prose:
  rooturl: ''
  siteurl: 'https://www.dta.gov.au/'
  media: '_assets/img/posts/'
  ignore:
    - _config.yml
    - _config-production.yml
    - _config-develop.yml
    - /manifest.yml
    - /manifest-production.yml
    - /manifest-develop.yml
    - /circle.yml
    - /_assets
    - /_data
    - /_layouts
    - /_includes
    - /_plugins
    - /_assets
    - /bin
    - /Gemfile
    - /Gemfile.lock
    - /.ruby-version
    - /.gitignore
    - /feed.xml
    - /Staticfile
    - /Staticfile.auth
    - README.md
    - Rakefile

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "hero-image"
        field:
          element: "text"
          label: "Hero image (filename only)"
      - name: "hero-image-alt"
        field:
          element: "text"
          label: "Hero image alt text"
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail image (filename only)"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Select Category"
          options:
            - name: "Blog"
              value: "blog"
            - name: "News"
              value: "[news]"
      - name: "tag"
        field:
          element: "select"
          label: "Tag"
          placeholder: "Select Tag"
          options:
            - name: "GOV.AU"
              value: "govau"
            - name: "Marketplace"
              value: "marketplace"
            - name: "DTA News"
              value: "dta-news"
